In [1]:
  import numpy as np

In [2]:
def matrix():
    import numpy as np
    a=int(input("Enter the starting range:" ))
    b=int(input("Enter the ending range:" ))
    order=int(input("Enter the order:" ))
    arr=np.arange(a,b)
    print(arr)
    arr1=np.vander(arr,order,increasing=True)
    print("Increasing is True\n", arr1)
    arr2=np.vander(arr,order,increasing=False)
    print("Increasing is False\n",arr2)

In [3]:
matrix()

Enter the starting range:1
Enter the ending range:6
Enter the order:5
[1 2 3 4 5]
Increasing is True
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Increasing is False
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [4]:
x=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
x

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [5]:
def moving_average(x):
    n= len(x)
    k=3
    list1=[]
    for i in range(n-k+1):
        z=np.array(x[i:i+k])
        t=0
        for j in z:
            t=t+j
        t=round(t/k,2)
        list1.append(t)
        i=i+1
    print(list1)

In [6]:
moving_average(x)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
